### ISSUE TITLE
security lab

### ISSUE THREAD

**Issue by michal-sebesta** [michal-sebesta/SEBC#6]

**Comment by michal-sebesta** [comment]
as we agreed I skipped to set TLS

**Comment by michal-sebesta** [comment]
ad we agreed I skipped setting TLS

**Comment by michal-sebesta** [comment]
SEBC/security/labs/cm_creds.png /- haven't find what to put to this file

**Comment by mfernest** [comment]
The requirement for `cm_creds.png` was removed, the stub file wasn't.

**C**ompleted.
